name: Run Makefile

on:
  push:

  pull_request:

  workflow_dispatch:
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install ldid

      - name: Compile
        run: make
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bakera1n
          path: packages/bakera1n.ipa
